
#pragma once
#ifndef CONSTRAINTS_WEBSERV_HPP
# define CONSTRAINTS_WEBSERV_HPP

#define CONSTRAINT_ARGC_MIN_VALUE 2
#define CONSTRAINT_ARGC_MAX_VALUE 4
#define CONSTRAINT_CONF_EXTENSION ".conf"

#endif //CONSTRAINTS_WEBSERV_HPP